// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: alumni_message.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Alumni struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Nim            string `protobuf:"bytes,4,opt,name=nim,proto3" json:"nim,omitempty"`
	Nik            string `protobuf:"bytes,5,opt,name=nik,proto3" json:"nik,omitempty"`
	PlaceOdBirth   string `protobuf:"bytes,6,opt,name=place_od_birth,json=placeOdBirth,proto3" json:"place_od_birth,omitempty"`
	DateOfBirth    string `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	MajorStudy     string `protobuf:"bytes,8,opt,name=major_study,json=majorStudy,proto3" json:"major_study,omitempty"`
	GraduationYear uint32 `protobuf:"varint,9,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	NoIjazah       string `protobuf:"bytes,10,opt,name=no_ijazah,json=noIjazah,proto3" json:"no_ijazah,omitempty"`
	Phone          string `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	Created        string `protobuf:"bytes,12,opt,name=created,proto3" json:"created,omitempty"`
	Updated        string `protobuf:"bytes,13,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *Alumni) Reset() {
	*x = Alumni{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alumni_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alumni) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alumni) ProtoMessage() {}

func (x *Alumni) ProtoReflect() protoreflect.Message {
	mi := &file_alumni_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alumni.ProtoReflect.Descriptor instead.
func (*Alumni) Descriptor() ([]byte, []int) {
	return file_alumni_message_proto_rawDescGZIP(), []int{0}
}

func (x *Alumni) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alumni) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Alumni) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alumni) GetNim() string {
	if x != nil {
		return x.Nim
	}
	return ""
}

func (x *Alumni) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *Alumni) GetPlaceOdBirth() string {
	if x != nil {
		return x.PlaceOdBirth
	}
	return ""
}

func (x *Alumni) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Alumni) GetMajorStudy() string {
	if x != nil {
		return x.MajorStudy
	}
	return ""
}

func (x *Alumni) GetGraduationYear() uint32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

func (x *Alumni) GetNoIjazah() string {
	if x != nil {
		return x.NoIjazah
	}
	return ""
}

func (x *Alumni) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Alumni) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Alumni) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

type AlumniList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alumni    []*Alumni  `protobuf:"bytes,1,rep,name=alumni,proto3" json:"alumni,omitempty"`
	ListInput *ListInput `protobuf:"bytes,2,opt,name=list_input,json=listInput,proto3" json:"list_input,omitempty"`
}

func (x *AlumniList) Reset() {
	*x = AlumniList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alumni_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlumniList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlumniList) ProtoMessage() {}

func (x *AlumniList) ProtoReflect() protoreflect.Message {
	mi := &file_alumni_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlumniList.ProtoReflect.Descriptor instead.
func (*AlumniList) Descriptor() ([]byte, []int) {
	return file_alumni_message_proto_rawDescGZIP(), []int{1}
}

func (x *AlumniList) GetAlumni() []*Alumni {
	if x != nil {
		return x.Alumni
	}
	return nil
}

func (x *AlumniList) GetListInput() *ListInput {
	if x != nil {
		return x.ListInput
	}
	return nil
}

var File_alumni_message_proto protoreflect.FileDescriptor

var file_alumni_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x02, 0x0a, 0x06, 0x41, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x69, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x69, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x6b,
	0x12, 0x24, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x6f, 0x64, 0x5f, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4f,
	0x64, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6f,
	0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61,
	0x6a, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x53, 0x74, 0x75, 0x64, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x67,
	0x72, 0x61, 0x64, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x67, 0x72, 0x61, 0x64, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x59, 0x65, 0x61, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x5f, 0x69, 0x6a, 0x61, 0x7a, 0x61,
	0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x49, 0x6a, 0x61, 0x7a, 0x61,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x64, 0x0a, 0x0a, 0x41,
	0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x6c, 0x75,
	0x6d, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x52, 0x06, 0x61, 0x6c, 0x75, 0x6d, 0x6e, 0x69,
	0x12, 0x2f, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alumni_message_proto_rawDescOnce sync.Once
	file_alumni_message_proto_rawDescData = file_alumni_message_proto_rawDesc
)

func file_alumni_message_proto_rawDescGZIP() []byte {
	file_alumni_message_proto_rawDescOnce.Do(func() {
		file_alumni_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_alumni_message_proto_rawDescData)
	})
	return file_alumni_message_proto_rawDescData
}

var file_alumni_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alumni_message_proto_goTypes = []interface{}{
	(*Alumni)(nil),     // 0: proto.Alumni
	(*AlumniList)(nil), // 1: proto.AlumniList
	(*ListInput)(nil),  // 2: proto.ListInput
}
var file_alumni_message_proto_depIdxs = []int32{
	0, // 0: proto.AlumniList.alumni:type_name -> proto.Alumni
	2, // 1: proto.AlumniList.list_input:type_name -> proto.ListInput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alumni_message_proto_init() }
func file_alumni_message_proto_init() {
	if File_alumni_message_proto != nil {
		return
	}
	file_generic_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_alumni_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alumni); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alumni_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlumniList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alumni_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alumni_message_proto_goTypes,
		DependencyIndexes: file_alumni_message_proto_depIdxs,
		MessageInfos:      file_alumni_message_proto_msgTypes,
	}.Build()
	File_alumni_message_proto = out.File
	file_alumni_message_proto_rawDesc = nil
	file_alumni_message_proto_goTypes = nil
	file_alumni_message_proto_depIdxs = nil
}
