// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: alumni_message.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Alumni struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       uint64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name         string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Nik          string         `protobuf:"bytes,4,opt,name=nik,proto3" json:"nik,omitempty"`
	PlaceOfBirth string         `protobuf:"bytes,5,opt,name=place_of_birth,json=placeOfBirth,proto3" json:"place_of_birth,omitempty"`
	DateOfBirth  string         `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Phone        string         `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Certificates []*Certificate `protobuf:"bytes,8,rep,name=certificates,proto3" json:"certificates,omitempty"`
	Created      string         `protobuf:"bytes,9,opt,name=created,proto3" json:"created,omitempty"`
	Updated      string         `protobuf:"bytes,10,opt,name=updated,proto3" json:"updated,omitempty"`
	Email        string         `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Alumni) Reset() {
	*x = Alumni{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alumni_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alumni) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alumni) ProtoMessage() {}

func (x *Alumni) ProtoReflect() protoreflect.Message {
	mi := &file_alumni_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alumni.ProtoReflect.Descriptor instead.
func (*Alumni) Descriptor() ([]byte, []int) {
	return file_alumni_message_proto_rawDescGZIP(), []int{0}
}

func (x *Alumni) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alumni) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Alumni) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alumni) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *Alumni) GetPlaceOfBirth() string {
	if x != nil {
		return x.PlaceOfBirth
	}
	return ""
}

func (x *Alumni) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Alumni) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Alumni) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *Alumni) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Alumni) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *Alumni) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AlumniListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alumni    *Alumni    `protobuf:"bytes,1,opt,name=alumni,proto3" json:"alumni,omitempty"`
	ListInput *ListInput `protobuf:"bytes,2,opt,name=list_input,json=listInput,proto3" json:"list_input,omitempty"`
}

func (x *AlumniListResponse) Reset() {
	*x = AlumniListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alumni_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlumniListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlumniListResponse) ProtoMessage() {}

func (x *AlumniListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alumni_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlumniListResponse.ProtoReflect.Descriptor instead.
func (*AlumniListResponse) Descriptor() ([]byte, []int) {
	return file_alumni_message_proto_rawDescGZIP(), []int{1}
}

func (x *AlumniListResponse) GetAlumni() *Alumni {
	if x != nil {
		return x.Alumni
	}
	return nil
}

func (x *AlumniListResponse) GetListInput() *ListInput {
	if x != nil {
		return x.ListInput
	}
	return nil
}

var File_alumni_message_proto protoreflect.FileDescriptor

var file_alumni_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb9, 0x02, 0x0a, 0x06, 0x41, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12,
	0x22, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69,
	0x72, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x52, 0x0c, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x6c, 0x0a, 0x12, 0x41,
	0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x75, 0x6d, 0x6e, 0x69,
	0x52, 0x06, 0x61, 0x6c, 0x75, 0x6d, 0x6e, 0x69, 0x12, 0x2f, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x09,
	0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alumni_message_proto_rawDescOnce sync.Once
	file_alumni_message_proto_rawDescData = file_alumni_message_proto_rawDesc
)

func file_alumni_message_proto_rawDescGZIP() []byte {
	file_alumni_message_proto_rawDescOnce.Do(func() {
		file_alumni_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_alumni_message_proto_rawDescData)
	})
	return file_alumni_message_proto_rawDescData
}

var file_alumni_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alumni_message_proto_goTypes = []interface{}{
	(*Alumni)(nil),             // 0: proto.Alumni
	(*AlumniListResponse)(nil), // 1: proto.AlumniListResponse
	(*Certificate)(nil),        // 2: proto.Certificate
	(*ListInput)(nil),          // 3: proto.ListInput
}
var file_alumni_message_proto_depIdxs = []int32{
	2, // 0: proto.Alumni.certificates:type_name -> proto.Certificate
	0, // 1: proto.AlumniListResponse.alumni:type_name -> proto.Alumni
	3, // 2: proto.AlumniListResponse.list_input:type_name -> proto.ListInput
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_alumni_message_proto_init() }
func file_alumni_message_proto_init() {
	if File_alumni_message_proto != nil {
		return
	}
	file_generic_message_proto_init()
	file_certificate_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_alumni_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alumni); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alumni_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlumniListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alumni_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alumni_message_proto_goTypes,
		DependencyIndexes: file_alumni_message_proto_depIdxs,
		MessageInfos:      file_alumni_message_proto_msgTypes,
	}.Build()
	File_alumni_message_proto = out.File
	file_alumni_message_proto_rawDesc = nil
	file_alumni_message_proto_goTypes = nil
	file_alumni_message_proto_depIdxs = nil
}
