package constant

const (
	USERTYPE_ALUMNI    uint32 = 1
	USERTYPE_APPRAISER uint32 = 2
	USERTYPE_ADMIN     uint32 = 3
	USERTYPE_PEJABAT   uint32 = 4
)

const (
	LEGALIZE_STATUS_REJECTED uint = 0
	LEGALIZE_STATUS_SUBMIT   uint = 1
	LEGALIZE_STATUS_VERIFIED uint = 2
	LEGALIZE_STATUS_APPROVED uint = 3
)
