export const Jurusan = [
  {id: 1, title: 'Jurusan Analisis Kesehatan/TLM'},
  {id: 2, title: 'Jurusan Farmasi'},
  {id: 3, title: 'Prodi D4 Gizi'},
  {id: 4, title: 'Prodi D3 Gizi'},
  {id: 5, title: 'Prodi D4 Keperawatan'},
  {id: 6, title: 'Prodi D3 Keperawatan Medan'},
  {id: 7, title: 'Jurusan Kesehatan Gigi'},
  {id: 8, title: 'Prodi D4 Sanitasi'},
  {id: 9, title: 'Prodi D3 Sanitasi'},
  {id: 10, title: 'Prodi D4 Kebidanan'},
  {id: 11, title: 'Prodi D3 Kebidanan Medan'},
  {id: 12, title: 'Prodi D3 Kebidanan P. Sidimpuan'},
  {id: 13, title: 'Prodi D3 Kebidanan P. Siantar'},
  {id: 14, title: 'Prodi D3 Kebidanan Tarutung'},
  {id: 15, title: 'Prodi D3 Kebidanan Karo'},
  {id: 16, title: 'Prodi D3 Keperawatan Gunung Sitoli'},
  {id: 17, title: 'Prodi D3 Keperawatan Dairi'},
  {id: 18, title: 'Prodi D3 Keperawatan Sibolga'},
  {id: 19, title: 'Prodi Profesi Bidan'},
];
