// source: legalize_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var alumni_message_pb = require('./alumni_message_pb.js');
goog.object.extend(proto, alumni_message_pb);
var certificate_message_pb = require('./certificate_message_pb.js');
goog.object.extend(proto, certificate_message_pb);
var generic_message_pb = require('./generic_message_pb.js');
goog.object.extend(proto, generic_message_pb);
goog.exportSymbol('proto.proto.Legalize', null, global);
goog.exportSymbol('proto.proto.LegalizeListResponse', null, global);
goog.exportSymbol('proto.proto.Legalizes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Legalize = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.Legalize, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.Legalize.displayName = 'proto.proto.Legalize';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.LegalizeListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.LegalizeListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.LegalizeListResponse.displayName = 'proto.proto.LegalizeListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Legalizes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.Legalizes.repeatedFields_, null);
};
goog.inherits(proto.proto.Legalizes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.Legalizes.displayName = 'proto.proto.Legalizes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Legalize.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Legalize.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Legalize} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Legalize.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    alumni: (f = msg.getAlumni()) && alumni_message_pb.Alumni.toObject(includeInstance, f),
    certificate: (f = msg.getCertificate()) && certificate_message_pb.Certificate.toObject(includeInstance, f),
    ijazah: jspb.Message.getFieldWithDefault(msg, 4, ""),
    transcript: jspb.Message.getFieldWithDefault(msg, 5, ""),
    isOffline: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    isVerified: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    isApproved: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    verifiedBy: jspb.Message.getFieldWithDefault(msg, 9, 0),
    approvedBy: jspb.Message.getFieldWithDefault(msg, 10, 0),
    verifiedAt: jspb.Message.getFieldWithDefault(msg, 11, ""),
    approvedAt: jspb.Message.getFieldWithDefault(msg, 12, ""),
    ijazahSigned: jspb.Message.getFieldWithDefault(msg, 13, ""),
    transcriptSigned: jspb.Message.getFieldWithDefault(msg, 14, ""),
    status: jspb.Message.getFieldWithDefault(msg, 15, 0),
    rating: jspb.Message.getFieldWithDefault(msg, 16, 0),
    created: jspb.Message.getFieldWithDefault(msg, 17, ""),
    updated: jspb.Message.getFieldWithDefault(msg, 18, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Legalize}
 */
proto.proto.Legalize.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Legalize;
  return proto.proto.Legalize.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Legalize} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Legalize}
 */
proto.proto.Legalize.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = new alumni_message_pb.Alumni;
      reader.readMessage(value,alumni_message_pb.Alumni.deserializeBinaryFromReader);
      msg.setAlumni(value);
      break;
    case 3:
      var value = new certificate_message_pb.Certificate;
      reader.readMessage(value,certificate_message_pb.Certificate.deserializeBinaryFromReader);
      msg.setCertificate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setIjazah(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTranscript(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsOffline(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsVerified(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsApproved(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setVerifiedBy(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setApprovedBy(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setVerifiedAt(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setApprovedAt(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setIjazahSigned(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setTranscriptSigned(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStatus(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRating(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreated(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Legalize.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Legalize.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Legalize} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Legalize.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getAlumni();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      alumni_message_pb.Alumni.serializeBinaryToWriter
    );
  }
  f = message.getCertificate();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      certificate_message_pb.Certificate.serializeBinaryToWriter
    );
  }
  f = message.getIjazah();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTranscript();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIsOffline();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getIsVerified();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getIsApproved();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getVerifiedBy();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getApprovedBy();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getVerifiedAt();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getApprovedAt();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getIjazahSigned();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getTranscriptSigned();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeUint32(
      15,
      f
    );
  }
  f = message.getRating();
  if (f !== 0) {
    writer.writeUint32(
      16,
      f
    );
  }
  f = message.getCreated();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getUpdated();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.proto.Legalize.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Alumni alumni = 2;
 * @return {?proto.proto.Alumni}
 */
proto.proto.Legalize.prototype.getAlumni = function() {
  return /** @type{?proto.proto.Alumni} */ (
    jspb.Message.getWrapperField(this, alumni_message_pb.Alumni, 2));
};


/**
 * @param {?proto.proto.Alumni|undefined} value
 * @return {!proto.proto.Legalize} returns this
*/
proto.proto.Legalize.prototype.setAlumni = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.clearAlumni = function() {
  return this.setAlumni(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Legalize.prototype.hasAlumni = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Certificate certificate = 3;
 * @return {?proto.proto.Certificate}
 */
proto.proto.Legalize.prototype.getCertificate = function() {
  return /** @type{?proto.proto.Certificate} */ (
    jspb.Message.getWrapperField(this, certificate_message_pb.Certificate, 3));
};


/**
 * @param {?proto.proto.Certificate|undefined} value
 * @return {!proto.proto.Legalize} returns this
*/
proto.proto.Legalize.prototype.setCertificate = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.clearCertificate = function() {
  return this.setCertificate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Legalize.prototype.hasCertificate = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string ijazah = 4;
 * @return {string}
 */
proto.proto.Legalize.prototype.getIjazah = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setIjazah = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string transcript = 5;
 * @return {string}
 */
proto.proto.Legalize.prototype.getTranscript = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setTranscript = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool is_offline = 6;
 * @return {boolean}
 */
proto.proto.Legalize.prototype.getIsOffline = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setIsOffline = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool is_verified = 7;
 * @return {boolean}
 */
proto.proto.Legalize.prototype.getIsVerified = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setIsVerified = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool is_approved = 8;
 * @return {boolean}
 */
proto.proto.Legalize.prototype.getIsApproved = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setIsApproved = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional uint64 verified_by = 9;
 * @return {number}
 */
proto.proto.Legalize.prototype.getVerifiedBy = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setVerifiedBy = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint64 approved_by = 10;
 * @return {number}
 */
proto.proto.Legalize.prototype.getApprovedBy = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setApprovedBy = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string verified_at = 11;
 * @return {string}
 */
proto.proto.Legalize.prototype.getVerifiedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setVerifiedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string approved_at = 12;
 * @return {string}
 */
proto.proto.Legalize.prototype.getApprovedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setApprovedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string ijazah_signed = 13;
 * @return {string}
 */
proto.proto.Legalize.prototype.getIjazahSigned = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setIjazahSigned = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string transcript_signed = 14;
 * @return {string}
 */
proto.proto.Legalize.prototype.getTranscriptSigned = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setTranscriptSigned = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional uint32 status = 15;
 * @return {number}
 */
proto.proto.Legalize.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional uint32 rating = 16;
 * @return {number}
 */
proto.proto.Legalize.prototype.getRating = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setRating = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string created = 17;
 * @return {string}
 */
proto.proto.Legalize.prototype.getCreated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setCreated = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string updated = 18;
 * @return {string}
 */
proto.proto.Legalize.prototype.getUpdated = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Legalize} returns this
 */
proto.proto.Legalize.prototype.setUpdated = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.LegalizeListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.LegalizeListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.LegalizeListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.LegalizeListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    legalize: (f = msg.getLegalize()) && proto.proto.Legalize.toObject(includeInstance, f),
    listInput: (f = msg.getListInput()) && generic_message_pb.ListInput.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.LegalizeListResponse}
 */
proto.proto.LegalizeListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.LegalizeListResponse;
  return proto.proto.LegalizeListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.LegalizeListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.LegalizeListResponse}
 */
proto.proto.LegalizeListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.Legalize;
      reader.readMessage(value,proto.proto.Legalize.deserializeBinaryFromReader);
      msg.setLegalize(value);
      break;
    case 2:
      var value = new generic_message_pb.ListInput;
      reader.readMessage(value,generic_message_pb.ListInput.deserializeBinaryFromReader);
      msg.setListInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.LegalizeListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.LegalizeListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.LegalizeListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.LegalizeListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLegalize();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.proto.Legalize.serializeBinaryToWriter
    );
  }
  f = message.getListInput();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      generic_message_pb.ListInput.serializeBinaryToWriter
    );
  }
};


/**
 * optional Legalize Legalize = 1;
 * @return {?proto.proto.Legalize}
 */
proto.proto.LegalizeListResponse.prototype.getLegalize = function() {
  return /** @type{?proto.proto.Legalize} */ (
    jspb.Message.getWrapperField(this, proto.proto.Legalize, 1));
};


/**
 * @param {?proto.proto.Legalize|undefined} value
 * @return {!proto.proto.LegalizeListResponse} returns this
*/
proto.proto.LegalizeListResponse.prototype.setLegalize = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.LegalizeListResponse} returns this
 */
proto.proto.LegalizeListResponse.prototype.clearLegalize = function() {
  return this.setLegalize(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.LegalizeListResponse.prototype.hasLegalize = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ListInput list_input = 2;
 * @return {?proto.proto.ListInput}
 */
proto.proto.LegalizeListResponse.prototype.getListInput = function() {
  return /** @type{?proto.proto.ListInput} */ (
    jspb.Message.getWrapperField(this, generic_message_pb.ListInput, 2));
};


/**
 * @param {?proto.proto.ListInput|undefined} value
 * @return {!proto.proto.LegalizeListResponse} returns this
*/
proto.proto.LegalizeListResponse.prototype.setListInput = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.LegalizeListResponse} returns this
 */
proto.proto.LegalizeListResponse.prototype.clearListInput = function() {
  return this.setListInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.LegalizeListResponse.prototype.hasListInput = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.Legalizes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Legalizes.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Legalizes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Legalizes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Legalizes.toObject = function(includeInstance, msg) {
  var f, obj = {
    legalizeList: jspb.Message.toObjectList(msg.getLegalizeList(),
    proto.proto.Legalize.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Legalizes}
 */
proto.proto.Legalizes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Legalizes;
  return proto.proto.Legalizes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Legalizes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Legalizes}
 */
proto.proto.Legalizes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.Legalize;
      reader.readMessage(value,proto.proto.Legalize.deserializeBinaryFromReader);
      msg.addLegalize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Legalizes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Legalizes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Legalizes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Legalizes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLegalizeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.proto.Legalize.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Legalize legalize = 1;
 * @return {!Array<!proto.proto.Legalize>}
 */
proto.proto.Legalizes.prototype.getLegalizeList = function() {
  return /** @type{!Array<!proto.proto.Legalize>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.Legalize, 1));
};


/**
 * @param {!Array<!proto.proto.Legalize>} value
 * @return {!proto.proto.Legalizes} returns this
*/
proto.proto.Legalizes.prototype.setLegalizeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.proto.Legalize=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.Legalize}
 */
proto.proto.Legalizes.prototype.addLegalize = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.proto.Legalize, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.Legalizes} returns this
 */
proto.proto.Legalizes.prototype.clearLegalizeList = function() {
  return this.setLegalizeList([]);
};


goog.object.extend(exports, proto.proto);
