export const PATH_URL = {
  BASE: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  KUISIONER: '/kuisioner',
  KUISIONER_ALUMNI: '/kuisioner-alumni',
  KESESUAIAN_PEKERJAAN: '/kesesuaian-pekerjaan',
  KUISIONER_SUDAH_BEKERJA: '/kuisioner-sudah-bekerja',
  KUISIONER_BELUM_BEKERJA: '/kuisioner-belum-bekerja',
  KUISIONER_LANJUT_KULIAH: '/kuisioner-lanjut-kuliah',
  UPLOAD_IJAZAH: '/upload',
  DOWNLOAD_IJAZAH: '/download',
  ALUMNI_REGISTRATION: '/alumni-registration',
  APPRAISER_REGISTRATION: '/appraiser-registration',
  KUISIONER_ALUMNI: '/kuisioner-alumni',
  LIST_ALUMNI: '/admin/list-alumni',
  E_LEGALISIR: '/admin/e-legalisir',
}